### ISSUE TITLE
Comment deletions

### ISSUE THREAD

**Issue by rebeccafoulger** [ebi-uniprot/Protein2GO#16]
I've found it a bit too easy to delete paper and protein comments (other people's included).

In the paper-view and protein-view, could we have a 'warning' before a comment is deleted, please? I think this already exists for annotation-specific comments.

Thank you!

**Comment by tonysawfordebi** [comment]
Done.

**Comment by mcourtot** [comment]
hm - I was about to comment that I'm not sure I wanted yet an extra popup :)

**Comment by tonysawfordebi** [comment]
I've got popups, and I'm not afraid to use them...

**Comment by monicacecilia** [comment]
@tonysawfordebi @mcourtot 
hehehe :bowtie: you guys are making me chuckle.

**Comment by tonysawfordebi** [comment]
Our work here is done.
