### ISSUE TITLE
Approving PRIV ISS annotations

### ISSUE THREAD

**Issue by rachhuntley** [ebi-uniprot/Protein2GO#18]
Hello,

Barbara has transferred some annotations by ISS from BHFL-assigned annotations and because she is undergoing training these ISS annotations are PRIV. However, there is no way for me to approve these annotations, see the Protein2GO record for URS000075DE64_9606.

Thanks,
Rachael.

**Comment by tonysawfordebi** [comment]
Hmmm...
Can you try updating the original BHFL annotation (change the source to PRIV & then back again, maybe) to see whether the update trickles down to the ISS annotations?

**Comment by rachhuntley** [comment]
Yes, that works. Likely to be a bit tedious though.

**Comment by tonysawfordebi** [comment]
Yes - there's clearly a problem here, so I'll do some investigating, but at least there's a workaround.

**Comment by rachhuntley** [comment]
Great, thanks.

**Comment by tonysawfordebi** [comment]
I've just put a fix in place for this - can you see whether it lets you approve Barbara's annotations now, please?

**Comment by rachhuntley** [comment]
Yes, tested and working perfectly. 
Thanks!

**Comment by tonysawfordebi** [comment]
Excellent - closing the ticket.
