### ISSUE TITLE
highlighting IPI pairs

### ISSUE THREAD

**Issue by NancyCampbell** [ebi-uniprot/Protein2GO#2]
Not urgent
Hi Tony,
IPI pair A+B, when I tick the box next to A (PCSK9 in example below), B lights up in blue. But when I tick the box next to B (LDLR in example), A does not light up.
I will try to attach a screenshot here, here we go:
![screen shot 2015-06-30 at 10 14 25](https://cloud.githubusercontent.com/assets/12081136/8427665/18bb7fc2-1f11-11e5-8d83-2bfcc7be71fe.png)
![screen shot 2015-06-30 at 10 13 52](https://cloud.githubusercontent.com/assets/12081136/8427666/18bc3e30-1f11-11e5-9b6a-42d5a969be33.png)
Thanks Tony.
Nancy

**Comment by tonysawfordebi** [comment]
Hi Nancy,

Unless I've misunderstood what you're doing, I've not been able to
duplicate the behaviour that you described - I tried all kinds of random
selections, and in all cases the highlighting did what I expected it to.

Can you refresh your browser and try again, please?

Cheers,
Tony

**Comment by NancyCampbell** [comment]
Hi Tony,
I refreshed and it is working now. Thanks Tony. 
But now the IntAct annotation shows a comment in the 'with' field and a lot of red balls appeared!
![screen shot 2015-06-30 at 13 53 59](https://cloud.githubusercontent.com/assets/12081136/8431187/ab908bd0-1f2f-11e5-8605-9602fe0dc270.png)
Thanks Tony.

**Comment by tonysawfordebi** [comment]
Hi Nancy,

Yes, there's a known issue with some of the annotation_extension
relations, following an update to one of the GO definition files;
everything should return to normal after tonight's QuickGO update
(which, realistically, means somewhere around lunchtime tomorrow).

Cheers,
Tony

**Comment by NancyCampbell** [comment]
Thanks Tony. Sorry I was too hasty.
