### ISSUE TITLE
cookie not getting saved permanently on my firefox 49.0.2

### ISSUE THREAD

**Issue by NancyCampbell** [ebi-uniprot/Protein2GO#21]
Hi Tony,
I can save the cookie and it looks like it has been saved. However, when I open a new tab, i am asked to save the cookie again.
I feel it coincided with installing the latest firefox but my memory fails me these days so I could be wrong.
It is not urgent or important but I thought to ask in case there is a quick fix.
Thanks a lot
Nanyc

**Comment by tonysawfordebi** [comment]
Hi Nancy (and welcome back, btw),

I suspect that what you're doing is using a form of the P2G URL that includes a parameter that looks something like "&SSOID1=1234_1130AB93E49D3F4B". If that's the case, then P2G assumes that it's the first time you've used the tool, and that your cookie has not been set.

The "Welcome..." email that you will have received when your account was first set up includes two links: the first includes the SSOID1 parameter, and should only be used the first time you use the tool in any browser; the second doesn't include it, and is the one that you should bookmark for future use.

If you can't find that email, let me know & I'll re-send it.

**Comment by NancyCampbell** [comment]
Hi Tony,
Thank you. It is good to be back :-)
You are prefectly right and I updated my bookmark (it was working fine before so I must have fiddled with it recently - which I don't remember (my memory fails me these days!!! meh!!)- and broke it)!
Merci beaucoup and mucho gracias
Nancy

**Comment by tonysawfordebi** [comment]
De nada :)
