### ISSUE TITLE
receiving emails wrt deleted priv annotations

### ISSUE THREAD

**Issue by NancyCampbell** [ebi-uniprot/Protein2GO#22]
Hi,

I deleted priv annotations and I checked that they are still in the deleted section P2G. However, this does not seem to have stopped the reminder emails coming through.
    
I don’t seem to be able to change priv to bhfl while the annotations are still in the deleted section, so is the only option to re-instate the annotations, change to bhfl, then delete again?

Thanks for your help

Nancy

@RLovering

**Comment by tonysawfordebi** [comment]
Hi Nancy,

What emails are you referring to?

**Comment by NancyCampbell** [comment]
Ruth received the email which she then forwards to me.

The email title is [UniProt-GOA] Report on PRIV annotations for which r.lovering@ucl.ac.uk is the designated checker.

shall I put a screenshot?

thanks Tony

**Comment by tonysawfordebi** [comment]
No, it's OK - I have a copy.

Which annotations in particular are you referring to?

**Comment by tonysawfordebi** [comment]
I've just re-run the query that the report uses, and it doesn't find any PRIV annotations that you made. When did you delete them? Was it after the 15th of August, which is when the last email was sent out?

**Comment by NancyCampbell** [comment]
I deleted them on the 16th of August and the email from Ruth is dated 15th of August. She sent me the email, hence I deleted them.

**Comment by RLovering** [comment]
Hi Both

I am so sorry for wasting your time. I thought I had filed all my Protein2GO old messages and was working on the train, which always seems to limit my peripheral vision. Then I checked one of the deleted entries at work and it had a July date so foolishly assumed the whole lot were deleted at the same time.

long story short --- yes I sent the same error report to Nancy twice

Sorry 

Ruth

**Comment by tonysawfordebi** [comment]
Bloody users :)
