### ISSUE TITLE
Not possible to add an extension in a validated annotation

### ISSUE THREAD

**Issue by lbreuza** [ebi-uniprot/Protein2GO#28]
Hi,
I was not able to add an extension to an existing annotation.
Best, Lionel

**Comment by alexsign** [comment]
Hi Lionel,

We had an issue since this morning, but it's resolved now. Please let me 
know if it's still the issue for you.

Best regards,

Alex

**Comment by lbreuza** [comment]
Thank you Alex,
it is working now while it did not work 5 minutes ago.
All good, I close the ticket.
Lionel
