### ISSUE TITLE
comment to checker field

### ISSUE THREAD

**Issue by RLovering** [ebi-uniprot/Protein2GO#5]
Hi Tony

The synapse annotators (but do they annotate?) wondered if it would be possible for the annotation row comment to checker field to be visible for new curators to use when they create the annotation, rather than having to submit the annotation and then open a the speech bubble link to add a comment.

I realise that for trained curators it would be a nightmare to have this additional annotation field visible in the editing section, but for new curators it would make it easier to add a comment supporting their annotation, and might even remind them that this needs to be added.

So I guess I am just requesting a field to be visible to new curators until they no longer have PRIV status, at which point the field would disappear.

Probably not possible.. but I just thought I'd check

Best

Ruth

**Comment by tonysawfordebi** [comment]
Hi Ruth,

The ability to create a comment (of any kind, not just Feedback To 
Checker ones) at the time when an annotation is created *might* be a 
useful additional feature, but it would not be a trivial thing to 
implement, and I'm not sure it's worth the effort just to save one click.

And no, there are currently no annotations from the synapse annotators.

Cheers,
Tony

**Comment by RLovering** [comment]
Hi Tony
Thanks for letting me know, I'll close this and try and think of something else to bug you with!
Best
Ruth
